# -*- coding: utf-8 -*-
#
# ICEkit documentation build configuration file, created by
# sphinx-quickstart on Tue Dec 20 00:39:45 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

import sys
from os.path import abspath, dirname, join
from recommonmark.parser import CommonMarkParser
from django.conf import settings

sys.path.append(abspath(join(dirname(__file__), "_ext")))
settings.configure()

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'autodoc_raw',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst', '.md']
# source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'ICEkit'
copyright = u'2016, the Interaction Consortium'
author = u'the Interaction Consortium'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u'0.9'
# The full version, including alpha/beta/rc tags.
release = u'0.9'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = [
    '_build*',
    'Thumbs.db',
    '.DS_Store',
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'ICEkitdoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'ICEkit.tex', u'ICEkit Documentation',
     u'the Interaction Consortium', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'icekit', u'ICEkit Documentation',
     [author], 1)
]


# -- Options for Recommonmark integration ---------------------------------
source_parsers = {
    '.md': CommonMarkParser,
}


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'ICEkit', u'ICEkit Documentation',
     author, 'ICEkit', 'One line description of project.',
     'Miscellaneous'),
]

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'https://docs.python.org/': None}

rst_epilog = """
.. _issues: https://github.com/ic-labs/django-icekit/issues
.. |IC| replace:: Interaction Consortium
.. _IC: https://interaction.net.au
.. |the IC| replace:: the Interaction Consortium (IC)
.. _`the IC`: https://interaction.net.au
.. _GLAMkit: http://glamkit.com
.. _django-fluent: https://django-fluent.org/
.. _`Docker Cloud`: https://cloud.docker.com
.. _`Elastic Search`: https://www.elastic.co/
.. _django-reversion: https://django-reversion.readthedocs.io/en/stable/
.. _`Travis CI`: https://travis-ci.org/
.. _Travis: https://travis-ci.org/
.. _icekit-events: https://github.com/ic-labs/icekit-events/
.. _icekit-press-releases: https://github.com/ic-labs/icekit-press-releases/
.. _glamkit-sponsors: https://github.com/ic-labs/glamkit-sponsors/
.. _glamkit-collections: https://github.com/ic-labs/glamkit-collections/
.. _django-dynamic-fixture: http://paulocheque.github.io/django-dynamic-fixture/
"""
